### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by djarami** [ProjectOpenSea/ships-log#8]
I've spent hours trying to get this code to build to no avail and I get hundreds of these errors below.
I've tried upgrading to newer versions of node which does resolve the URL issue but then get a bunch of package conflicts of version version of the same package being required by some other packages.

It would be great If someone could provide the specific package-lock.json that works for them.

Issue seems to stem from the web3 pacakges.

It would be even better if someone from @ProjectOpenSea could push an updated version of this repo that works with the newer Nodejs.

```npm WARN old lockfile ReferenceError: URL is not defined
npm WARN old lockfile     at regKeyFromURI (/Users/davidj/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-fetch/auth.js:7:18)
npm WARN old lockfile     at getAuth (/Users/davidj/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-fetch/auth.js:49:18)
npm WARN old lockfile     at regFetch (/Users/davidj/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:55:16)
npm WARN old lockfile     at RemoteFetcher.[pacote.Fetcher._tarballFromResolved] (/Users/davidj/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/pacote/lib/remote.js:40:5)```

**Comment by djarami** [comment]
@radotzki Any chance you could post your package-lock.json file here and also what version of node you are using.
